### PR TITLE
Add a background for generated channel icons

### PR DESCRIPTION
**Pull request by dylanmccall**

### CODE REVIEW

**Comment by dylanmccall** [comment]
This generates icons like the following, which are perhaps nicer looking most of the time.

org learningequality Kolibri Channel 197934f144305350b5820c7c4dd8e194
org learningequality Kolibri Channel c9d7f950ab6b5a1199e3d6c10d7f0103
org learningequality Kolibri Channel 3e464ee12f6a50a781cddf59147b48b1

**Review by manuq — APPROVED** [review]
Excellent, good idea adding comments to the graphics maths.

**Comment by manuq** [comment]
@dylanmccall please next time attach the ticket URL to the commit message and PR message. I merged this and then realized.

**Comment by dylanmccall** [comment]
Oh, oops! Thanks :)

**Pull request merged**
